name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  run_tests:
    description: 'If true, run unit tests, otherwise skip them.'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup dotnet build tools
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0
          9.0

    - name: Restore dotnet dependencies
      shell: bash
      id: restore
      run: dotnet restore

    - name: Build
      shell: bash
      id: build
      run: dotnet build

    - name: Run Tests
      if: steps.build.outcome == 'success' && inputs.run_tests == 'true'
      shell: bash
      run: dotnet test

    - name: Build Documentation
      if: steps.build.outcome == 'success'
      uses: ./.github/actions/build-docs
