name: Publish Package
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'If true, run unit tests, otherwise skip them.'
        type: boolean
        default: true
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true
  workflow_call:
    inputs:
      run_tests:
        description: 'If true, run unit tests, otherwise skip them.'
        required: false
        type: boolean
        default: true
      dry_run:
        description: 'Is this a dry run. If so no package will be published.'
        type: boolean
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: CI check
        uses: ./.github/actions/ci
        with:
          run_tests: ${{ inputs.run_tests }}

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.1.0
        name: Get secrets
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/releasing/nuget/api_key = NUGET_API_KEY'

      - name: Release Build
        uses: ./.github/actions/release-build

      - name: Publish Nupkg
        uses: ./.github/actions/publish
        with:
          dry_run: ${{ inputs.dry_run }}
